### ISSUE TITLE
Interfaces for metrics/finding registration

### ISSUE THREAD

**Issue by moltob** [cqse/teamscale-client-python#1]
Before I can upload finding and metrics I need to register them, e.g. through service `add-external-metric-description` and `add-external-findings-group`. If I understand the current API correctly, this is not yet part of it.

Would it be possible to add this? Or do you expect users to go through the lower level PUT/... API?

**Comment by nihathrael** [comment]
I can add the requested services. These are mostly one shot operations which is why I did not include them at first, but adding them is no problem and a good idea.

**Comment by nihathrael** [comment]
These have been added recently.
