### ISSUE TITLE
PyPI serving only old version?

### ISSUE THREAD

**Issue by moltob** [cqse/teamscale-client-python#14]
Not sure why, but using pip to install this library from PyPI only gets me an old version 0.0.7 and a Windows 10 machine with Python 3.5. Here is some console output showing the issue:

```
(envmtrxrpt) E:\VbfMetricsReporting>pip install --upgrade teamscale-client==1.2.1
Collecting teamscale-client==1.2.1
  Could not find a version that satisfies the requirement teamscale-client==1.2.1 (from versions: 0.0.1.linux-x86_64, 0.0.2.linux-x86_64, 0.0.3.linux-x86_64, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7)
No matching distribution found for teamscale-client==1.2.1
```

As a result, standard dependency installation does not work.

Note: I am in a Portland hotel (@ Pycon :-) ), so this could theoretically be a network config issue, but I don't yet see how that would be possible.

**Comment by moltob** [comment]
As a side note: installing directly from Github does work fine:

```
(envmtrxrpt) E:\VbfMetricsReporting>pip install --upgrade https://github.com/cqse/teamscale-client-python/archive/master.zip
Collecting https://github.com/cqse/teamscale-client-python/archive/master.zip
  Downloading https://github.com/cqse/teamscale-client-python/archive/master.zip
     - 36kB 127kB/s
...
  Running setup.py install for teamscale-client
```

**Comment by nihathrael** [comment]
Can you retry? I added a source dist for the newest version.

**Comment by moltob** [comment]
Works. Thanks. By the way: you should crate binaries in wheel format instead via

```
python setup.py bdist_wheel
```

This installs faster (no building of pyc) and makes it easier on the user if at some point htere would be c-extensions or anything else advanced. Also it is the modern way of Python package distribution, see http://pythonwheels.com/.

**Comment by nihathrael** [comment]
Thanks for the tip. I've published wheel files. I also added a small make file with a publish_release target: https://github.com/cqse/teamscale-client-python/blob/master/Makefile

Hopefully this will help in always uploading all necessary targets.
