### ISSUE TITLE
Upload coverage reports

### ISSUE THREAD

**Issue by dpagano** [cqse/teamscale-client-python#16]
It would be nice if the Python client could upload coverage reports to Teamscale like from Jacoco.

**Comment by nihathrael** [comment]
This is already possible:
http://cqse.github.io/teamscale-client-python/teamscale_client.html#teamscale_client.client.TeamscaleClient.upload_coverage_data

Example:
https://github.com/cqse/teamscale-client-python/blob/master/examples/example_test_coverage_upload.py
